/*#############################################*/
/*1. PRÉPARATION ET NETTOYAGE                 #*/
/*#############################################*/
USE SOCCER;
GO

/* Suppression des objets (Ordre inverse des dépendances) */
IF OBJECT_ID('CHAMPIONS_LEAGUE.BUTS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LEAGUE.BUTS;
IF OBJECT_ID('CHAMPIONS_LEAGUE.MATCHS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LEAGUE.MATCHS;
IF OBJECT_ID('CHAMPIONS_LEAGUE.TRANSFERTS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LEAGUE.TRANSFERTS;
IF OBJECT_ID('CHAMPIONS_LEAGUE.JOUEURS_EQUIPE_SAISON', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LEAGUE.JOUEURS_EQUIPE_SAISON;
IF OBJECT_ID('CHAMPIONS_LEAGUE.ENTRAINEURS_EQUIPE_SAISON', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LEAGUE.ENTRAINEURS_EQUIPE_SAISON;
IF OBJECT_ID('CHAMPIONS_LEAGUE.SAISON_EQUIPES', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LEAGUE.SAISON_EQUIPES;
IF OBJECT_ID('CHAMPIONS_LEAGUE.JOURNEES', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LEAGUE.JOURNEES;
IF OBJECT_ID('CHAMPIONS_LEAGUE.EQUIPES', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LEAGUE.EQUIPES;
IF OBJECT_ID('CHAMPIONS_LEAGUE.JOUEURS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LEAGUE.JOUEURS;
IF OBJECT_ID('CHAMPIONS_LEAGUE.ENTRAINEURS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LEAGUE.ENTRAINEURS;
IF OBJECT_ID('CHAMPIONS_LEAGUE.STADES', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LEAGUE.STADES;
IF OBJECT_ID('CHAMPIONS_LEAGUE.POSTES_REFERENCE', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LEAGUE.POSTES_REFERENCE;
IF OBJECT_ID('CHAMPIONS_LEAGUE.TYPES_BUTS_REFERENCE', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LEAGUE.TYPES_BUTS_REFERENCE;
IF OBJECT_ID('CHAMPIONS_LEAGUE.SAISONS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LEAGUE.SAISONS;
GO

/*###############################################*/
/* 2. CRÉATION DES TABLES                       #*/
/*###############################################*/

/* TABLE CHAMPIONS_LEAGUE.POSTES_REFERENCE */
CREATE TABLE CHAMPIONS_LEAGUE.POSTES_REFERENCE (
    poste_id INT PRIMARY KEY,
    nomPoste VARCHAR(20) NOT NULL UNIQUE
);

/* TABLE CHAMPIONS_LEAGUE.TYPES_BUTS_REFERENCE */
CREATE TABLE CHAMPIONS_LEAGUE.TYPES_BUTS_REFERENCE (
    type_but_id INT PRIMARY KEY,
    nom_type_but VARCHAR(50) NOT NULL UNIQUE
);

/* TABLE CHAMPIONS_LEAGUE.STADES */
CREATE TABLE CHAMPIONS_LEAGUE.STADES (
    stade_id INT IDENTITY(1,1) PRIMARY KEY,
    nomStade VARCHAR(100) NOT NULL,
    villeStade VARCHAR(100) NOT NULL,
    paysStade VARCHAR(100) NOT NULL,
    capacite INTEGER
);

/* TABLE CHAMPIONS_LEAGUE.SAISONS */
CREATE TABLE CHAMPIONS_LEAGUE.SAISONS (
    saison_id INT IDENTITY(1,1) PRIMARY KEY,
    annee_debut INTEGER NOT NULL UNIQUE,
    annee_fin INTEGER NOT NULL UNIQUE
);

/* TABLE CHAMPIONS_LEAGUE.ENTRAINEURS */
CREATE TABLE CHAMPIONS_LEAGUE.ENTRAINEURS (
    entraineur_id INT IDENTITY(1,1) PRIMARY KEY,
    nomEntraineur VARCHAR(100) NOT NULL,
    prenomEntraineur VARCHAR(100),
    paysEntraineur VARCHAR(50)
);

/* TABLE CHAMPIONS_LEAGUE.JOUEURS */
CREATE TABLE CHAMPIONS_LEAGUE.JOUEURS (
    joueur_id INT PRIMARY KEY IDENTITY(1,1),
    nomJoueur VARCHAR(100) NOT NULL,
    prenomJoueur VARCHAR(100) NOT NULL,
    date_naissance DATE,
    poste_id INT REFERENCES CHAMPIONS_LEAGUE.POSTES_REFERENCE(poste_id),
    paysJoueur VARCHAR(50)
);

/* TABLE CHAMPIONS_LEAGUE.EQUIPES */
CREATE TABLE CHAMPIONS_LEAGUE.EQUIPES (
    equipe_id INT IDENTITY(1,1) PRIMARY KEY,
    nomEquipe VARCHAR(100) NOT NULL UNIQUE,
    abreviation VARCHAR(10) UNIQUE,
    stade_id INTEGER REFERENCES CHAMPIONS_LEAGUE.STADES(stade_id)
);

/* TABLE CHAMPIONS_LEAGUE.JOURNEES */
CREATE TABLE CHAMPIONS_LEAGUE.JOURNEES (
    saison_id INTEGER NOT NULL REFERENCES CHAMPIONS_LEAGUE.SAISONS(saison_id),
    numero_journee INTEGER NOT NULL,
    date_limite DATE,
    PRIMARY KEY (saison_id, numero_journee)
);

/* TABLE CHAMPIONS_LEAGUE.JOUEURS_EQUIPE_SAISON */
CREATE TABLE CHAMPIONS_LEAGUE.JOUEURS_EQUIPE_SAISON (
    contrat_id INT IDENTITY(1,1) PRIMARY KEY,
    saison_id INTEGER REFERENCES CHAMPIONS_LEAGUE.SAISONS(saison_id),
    joueur_id INTEGER REFERENCES CHAMPIONS_LEAGUE.JOUEURS(joueur_id),
    equipe_id INTEGER REFERENCES CHAMPIONS_LEAGUE.EQUIPES(equipe_id),
    date_arrivee DATE NOT NULL,
    
    /* Contrainte : Un joueur ne peut pas arriver deux fois dans un club (ou un autre) */
    /* à la même date précise pour la même saison.*/
    CONSTRAINT UQ_Joueur_Saison_Date UNIQUE (joueur_id, saison_id, date_arrivee)
);

/* TABLE CHAMPIONS_LEAGUE.ENTRAINEURS_EQUIPE_SAISON */
CREATE TABLE CHAMPIONS_LEAGUE.ENTRAINEURS_EQUIPE_SAISON (
    contrat_id INT IDENTITY(1,1) PRIMARY KEY,
    saison_id INTEGER REFERENCES CHAMPIONS_LEAGUE.SAISONS(saison_id),
    entraineur_id INTEGER REFERENCES CHAMPIONS_LEAGUE.ENTRAINEURS(entraineur_id),
    equipe_id INTEGER REFERENCES CHAMPIONS_LEAGUE.EQUIPES(equipe_id),
    date_arrivee DATE NOT NULL
);

/* TABLE CHAMPIONS_LEAGUE.SAISON_EQUIPES */
CREATE TABLE CHAMPIONS_LEAGUE.SAISON_EQUIPES (
    saison_id INTEGER REFERENCES CHAMPIONS_LEAGUE.SAISONS(saison_id),
    equipe_id INTEGER REFERENCES CHAMPIONS_LEAGUE.EQUIPES(equipe_id),
    PRIMARY KEY (saison_id, equipe_id)
);

/* TABLE CHAMPIONS_LEAGUE.MATCHS */
CREATE TABLE CHAMPIONS_LEAGUE.MATCHS (
    match_id INT PRIMARY KEY IDENTITY(1,1),
    saison_id INTEGER NOT NULL,
    numero_journee INTEGER NOT NULL,
    equipe_domicile_id INTEGER NOT NULL REFERENCES CHAMPIONS_LEAGUE.EQUIPES(equipe_id),
    equipe_exterieur_id INTEGER NOT NULL REFERENCES CHAMPIONS_LEAGUE.EQUIPES(equipe_id),
    stade_id INTEGER REFERENCES CHAMPIONS_LEAGUE.STADES(stade_id),
    date_match DATETIME NOT NULL,
    buts_domicile INTEGER DEFAULT 0,
    buts_exterieur INTEGER DEFAULT 0,
    CHECK (equipe_domicile_id <> equipe_exterieur_id),
    FOREIGN KEY (saison_id, numero_journee) REFERENCES CHAMPIONS_LEAGUE.JOURNEES (saison_id, numero_journee),
    UNIQUE (saison_id, numero_journee, equipe_domicile_id, equipe_exterieur_id)
);

/* TABLE CHAMPIONS_LEAGUE.BUTS */
CREATE TABLE CHAMPIONS_LEAGUE.BUTS (
    but_id INT IDENTITY(1,1) PRIMARY KEY,
    match_id INTEGER REFERENCES CHAMPIONS_LEAGUE.MATCHS(match_id),
    joueur_id INTEGER REFERENCES CHAMPIONS_LEAGUE.JOUEURS(joueur_id),
    equipe_but_id INTEGER REFERENCES CHAMPIONS_LEAGUE.EQUIPES(equipe_id),
    minute_but INTEGER NOT NULL,
    type_but_id INTEGER REFERENCES CHAMPIONS_LEAGUE.TYPES_BUTS_REFERENCE(type_but_id)
);

/* TABLE CHAMPIONS_LEAGUE.TRANSFERTS */
CREATE TABLE CHAMPIONS_LEAGUE.TRANSFERTS (
    transfert_id INT IDENTITY(1,1) PRIMARY KEY,
    joueur_id INTEGER REFERENCES CHAMPIONS_LEAGUE.JOUEURS(joueur_id),
    entraineur_id INTEGER REFERENCES CHAMPIONS_LEAGUE.ENTRAINEURS(entraineur_id),
    saison_id INTEGER NOT NULL REFERENCES CHAMPIONS_LEAGUE.SAISONS(saison_id),
    ancienne_equipe_id INTEGER REFERENCES CHAMPIONS_LEAGUE.EQUIPES(equipe_id),
    nouvelle_equipe_id INTEGER NOT NULL REFERENCES CHAMPIONS_LEAGUE.EQUIPES(equipe_id),
    date_transfert DATE NOT NULL,
    montant_transfert NUMERIC(15, 2),
    type_transfert VARCHAR(50) DEFAULT 'Définitif'
);
GO
