-- #############################################
-- 1. PRÉPARATION DU CONTEXTE
-- #############################################
USE SOCCER; 
GO

-- #############################################
-- 2. SUPPRESSION DES OBJETS (Ordre inverse)
-- #############################################

-- NIVEAU 1
IF OBJECT_ID('CHAMPIONS_LIGUE.Cartons', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.Cartons;
IF OBJECT_ID('CHAMPIONS_LIGUE.BUTS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.BUTS;
IF OBJECT_ID('CHAMPIONS_LIGUE.STATS_JOUEURS_MATCHS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.STATS_JOUEURS_MATCHS;

-- NIVEAU 2
IF OBJECT_ID('CHAMPIONS_LIGUE.MATCHS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.MATCHS;
IF OBJECT_ID('CHAMPIONS_LIGUE.TRANSFERTS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.TRANSFERTS;
IF OBJECT_ID('CHAMPIONS_LIGUE.PROMOTIONS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.PROMOTIONS;
IF OBJECT_ID('CHAMPIONS_LIGUE.RELEGATIONS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.RELEGATIONS;
IF OBJECT_ID('CHAMPIONS_LIGUE.CLASSEMENT', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.CLASSEMENT;
IF OBJECT_ID('CHAMPIONS_LIGUE.CLASSEMENT_BUTEURS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.CLASSEMENT_BUTEURS;

-- NIVEAU 3
IF OBJECT_ID('CHAMPIONS_LIGUE.JOUEURS_EQUIPE_SAISON', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.JOUEURS_EQUIPE_SAISON;
IF OBJECT_ID('CHAMPIONS_LIGUE.ENTRAINEURS_EQUIPE_SAISON', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.ENTRAINEURS_EQUIPE_SAISON;
IF OBJECT_ID('CHAMPIONS_LIGUE.SAISON_EQUIPES', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.SAISON_EQUIPES;

-- NIVEAU 4
IF OBJECT_ID('CHAMPIONS_LIGUE.JOURNEES', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.JOURNEES;

-- NIVEAU 5
IF OBJECT_ID('CHAMPIONS_LIGUE.EQUIPES', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.EQUIPES;
IF OBJECT_ID('CHAMPIONS_LIGUE.JOUEURS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.JOUEURS;
IF OBJECT_ID('CHAMPIONS_LIGUE.ENTRAINEURS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.ENTRAINEURS;

-- NIVEAU 6
IF OBJECT_ID('CHAMPIONS_LIGUE.SAISONS', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.SAISONS;
IF OBJECT_ID('CHAMPIONS_LIGUE.STADES', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.STADES;
IF OBJECT_ID('CHAMPIONS_LIGUE.POSTES_REFERENCE', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.POSTES_REFERENCE;
IF OBJECT_ID('CHAMPIONS_LIGUE.TYPES_BUTS_REFERENCE', 'U') IS NOT NULL DROP TABLE CHAMPIONS_LIGUE.TYPES_BUTS_REFERENCE;
GO

-- Suppression des Séquences
IF OBJECT_ID('CHAMPIONS_LIGUE.stade_id_seq', 'SO') IS NOT NULL DROP SEQUENCE CHAMPIONS_LIGUE.stade_id_seq;
IF OBJECT_ID('CHAMPIONS_LIGUE.saison_id_seq', 'SO') IS NOT NULL DROP SEQUENCE CHAMPIONS_LIGUE.saison_id_seq;
GO

-- #############################################
-- 3. CRÉATION DES TABLES
-- #############################################

CREATE SEQUENCE CHAMPIONS_LIGUE.stade_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CHAMPIONS_LIGUE.saison_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE CHAMPIONS_LIGUE.POSTES_REFERENCE (
    poste_id INT PRIMARY KEY,
    nomPoste VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE CHAMPIONS_LIGUE.STADES (
    stade_id INTEGER PRIMARY KEY DEFAULT NEXT VALUE FOR CHAMPIONS_LIGUE.stade_id_seq,
    nomStade VARCHAR(100) NOT NULL,
    villeStade VARCHAR(100) NOT NULL,
    paysStade VARCHAR(100) NOT NULL,
    capacite INTEGER
);

CREATE TABLE CHAMPIONS_LIGUE.SAISONS (
    saison_id INTEGER PRIMARY KEY DEFAULT NEXT VALUE FOR CHAMPIONS_LIGUE.saison_id_seq,
    annee_debut INTEGER NOT NULL UNIQUE,
    annee_fin INTEGER NOT NULL UNIQUE,
    CONSTRAINT chk_saison_duree CHECK (annee_fin = annee_debut + 1)
);

CREATE TABLE CHAMPIONS_LIGUE.JOUEURS (
    joueur_id INT PRIMARY KEY IDENTITY(1,1),
    nomJoueur VARCHAR(100) NOT NULL,
    prenomJoueur VARCHAR(100) NOT NULL,
    date_naissance DATE,
    poste_id INT,
    paysJoueur VARCHAR(50),
    FOREIGN KEY (poste_id) REFERENCES CHAMPIONS_LIGUE.POSTES_REFERENCE(poste_id)
);

CREATE TABLE CHAMPIONS_LIGUE.ENTRAINEURS (
    entraineur_id INTEGER PRIMARY KEY,
    nomEntraineur VARCHAR(100) NOT NULL,
    prenomEntraineur VARCHAR(100),
    date_naissance DATE,
    paysEntraineur VARCHAR(50)
);

CREATE TABLE CHAMPIONS_LIGUE.EQUIPES (
    equipe_id INTEGER PRIMARY KEY,
    nomEquipe VARCHAR(100) NOT NULL UNIQUE,
    abreviation VARCHAR(10) UNIQUE,
    annee_fondation INTEGER,
    paysEquipe VARCHAR(100),
    stade_id INTEGER REFERENCES CHAMPIONS_LIGUE.STADES(stade_id),
    CONSTRAINT chk_annee_fondation_valide CHECK (annee_fondation IS NULL OR annee_fondation <= YEAR(GETDATE()))
);

CREATE TABLE CHAMPIONS_LIGUE.JOURNEES (
    saison_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.SAISONS(saison_id),
    numero_journee INTEGER NOT NULL,
    date_limite DATE,
    CONSTRAINT chk_numero_journee CHECK (numero_journee >= 1 AND numero_journee <= 38),
    PRIMARY KEY (saison_id, numero_journee)
);

CREATE TABLE CHAMPIONS_LIGUE.TRANSFERTS (
    transfert_id INT PRIMARY KEY IDENTITY(1,1),
    joueur_id INTEGER REFERENCES CHAMPIONS_LIGUE.JOUEURS(joueur_id),
    entraineur_id INTEGER REFERENCES CHAMPIONS_LIGUE.ENTRAINEURS(entraineur_id),
    saison_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.SAISONS(saison_id),
    ancienne_equipe_id INTEGER REFERENCES CHAMPIONS_LIGUE.EQUIPES(equipe_id),
    nouvelle_equipe_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.EQUIPES(equipe_id),
    date_transfert DATE NOT NULL,
    duree_contrat_annees INTEGER,
    montant_transfert NUMERIC(15, 2),
    type_transfert VARCHAR(50) DEFAULT 'Définitif',
    CONSTRAINT CHK_JoueurOuEntraineur CHECK ((joueur_id IS NOT NULL AND entraineur_id IS NULL) OR (joueur_id IS NULL AND entraineur_id IS NOT NULL)),
    CONSTRAINT CHK_EquipeDifferente CHECK (ancienne_equipe_id IS NULL OR ancienne_equipe_id <> nouvelle_equipe_id)
);

CREATE TABLE CHAMPIONS_LIGUE.SAISON_EQUIPES (
    saison_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.SAISONS(saison_id),
    equipe_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.EQUIPES(equipe_id),
    PRIMARY KEY (saison_id, equipe_id)
);

CREATE TABLE CHAMPIONS_LIGUE.JOUEURS_EQUIPE_SAISON (
    contrat_saison_id INT PRIMARY KEY IDENTITY(1,1),
    saison_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.SAISONS(saison_id),
    joueur_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.JOUEURS(joueur_id),
    equipe_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.EQUIPES(equipe_id),
    date_arrivee DATE NOT NULL,
    date_depart DATE,
    UNIQUE (saison_id, joueur_id, equipe_id, date_arrivee)
);

CREATE TABLE CHAMPIONS_LIGUE.ENTRAINEURS_EQUIPE_SAISON (
    contrat_saison_id INT PRIMARY KEY IDENTITY(1,1),
    saison_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.SAISONS(saison_id),
    entraineur_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.ENTRAINEURS(entraineur_id),
    equipe_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.EQUIPES(equipe_id),
    date_arrivee DATE NOT NULL,
    date_depart DATE,
    UNIQUE (saison_id, entraineur_id, equipe_id, date_arrivee)
);

CREATE TABLE CHAMPIONS_LIGUE.MATCHS (
    match_id INT PRIMARY KEY IDENTITY(1,1),
    saison_id INTEGER NOT NULL,
    numero_journee INTEGER NOT NULL,
    equipe_domicile_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.EQUIPES(equipe_id),
    equipe_exterieur_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.EQUIPES(equipe_id),
    stade_id INTEGER REFERENCES CHAMPIONS_LIGUE.STADES(stade_id),
    date_match DATETIME NOT NULL,
    buts_domicile INTEGER DEFAULT 0,
    buts_exterieur INTEGER DEFAULT 0,
    FOREIGN KEY (saison_id, numero_journee) REFERENCES CHAMPIONS_LIGUE.JOURNEES (saison_id, numero_journee)
);

CREATE TABLE CHAMPIONS_LIGUE.TYPES_BUTS_REFERENCE (
    type_but_id INT PRIMARY KEY,
    nom_type_but VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE CHAMPIONS_LIGUE.BUTS (
    but_id INT PRIMARY KEY IDENTITY(1,1),
    match_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.MATCHS(match_id),
    joueur_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.JOUEURS(joueur_id),
    equipe_but_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.EQUIPES(equipe_id),
    minute_but INTEGER NOT NULL,
    type_but_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.TYPES_BUTS_REFERENCE(type_but_id)
);

CREATE TABLE CHAMPIONS_LIGUE.Cartons (
    carton_id INT PRIMARY KEY IDENTITY(1,1),
    match_id INT NOT NULL REFERENCES CHAMPIONS_LIGUE.MATCHS(match_id),
    minute_carton INT NOT NULL,
    type_carton VARCHAR(20) NOT NULL CHECK (type_carton IN ('Jaune', 'Rouge', 'Deuxieme_Jaune')),
    joueur_id INT REFERENCES CHAMPIONS_LIGUE.JOUEURS(joueur_id),
    entraineur_id INTEGER REFERENCES CHAMPIONS_LIGUE.ENTRAINEURS(entraineur_id),
    CONSTRAINT CHK_UnSeulBeneficiaire CHECK ((joueur_id IS NOT NULL AND entraineur_id IS NULL) OR (joueur_id IS NULL AND entraineur_id IS NOT NULL))
);

CREATE TABLE CHAMPIONS_LIGUE.STATS_JOUEURS_MATCHS (
    stats_match_id INTEGER IDENTITY(1,1) PRIMARY KEY, 
    match_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.MATCHS(match_id),
    joueur_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.JOUEURS(joueur_id),
    equipe_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.EQUIPES(equipe_id),
    buts_marques INTEGER NOT NULL DEFAULT 0,
    passes_decisives INTEGER NOT NULL DEFAULT 0,
    temps_jeu_minutes INTEGER,
    cartons_jaunes INTEGER NOT NULL DEFAULT 0,
    cartons_rouges INTEGER NOT NULL DEFAULT 0, 
    CONSTRAINT UQ_STATS_MATCH_JOUEUR UNIQUE (match_id, joueur_id)
);

CREATE TABLE CHAMPIONS_LIGUE.CLASSEMENT (
    saison_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.SAISONS(saison_id),
    equipe_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.EQUIPES(equipe_id),
    points INTEGER DEFAULT 0,
    matchs_joues INTEGER DEFAULT 0,
    victoires INTEGER DEFAULT 0,
    defaites INTEGER DEFAULT 0,
    nuls INTEGER DEFAULT 0,
    buts_marques INTEGER DEFAULT 0,
    buts_encaisses INTEGER DEFAULT 0,
    difference_buts INTEGER DEFAULT 0,
    PRIMARY KEY (saison_id, equipe_id)
);

CREATE TABLE CHAMPIONS_LIGUE.CLASSEMENT_BUTEURS (
    JOUEUR_ID INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.JOUEURS(joueur_id),
    SAISON_ID INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.SAISONS(saison_id), 
    NOMBRE_BUTS INT NOT NULL DEFAULT 0,
    PRIMARY KEY (JOUEUR_ID, SAISON_ID)
);

CREATE TABLE CHAMPIONS_LIGUE.RELEGATIONS (
    relegation_id INT PRIMARY KEY IDENTITY(1,1), 
    saison_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.SAISONS(saison_id),
    equipe_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.EQUIPES(equipe_id),
    classement_final INTEGER NOT NULL,
    UNIQUE (saison_id, equipe_id)
);

CREATE TABLE CHAMPIONS_LIGUE.PROMOTIONS (
    promotion_id INT PRIMARY KEY IDENTITY(1,1),
    saison_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.SAISONS(saison_id),
    equipe_id INTEGER NOT NULL REFERENCES CHAMPIONS_LIGUE.EQUIPES(equipe_id),
    statut VARCHAR(50) DEFAULT 'Promue',
    UNIQUE (saison_id, equipe_id)
);
GO