{{ config(materialized='table') }}

WITH resultats_matchs AS (
    SELECT 
        "SAISON_ID",
        "EQUIPE_DOMICILE_ID" AS "EQUIPE_ID",
        "BUTS_DOMICILE" AS "BUTS_POUR",
        "BUTS_EXTERIEUR" AS "BUTS_CONTRE",
        CASE WHEN "RESULTAT" = 'VICTOIRE_DOMICILE' THEN 3 WHEN "RESULTAT" = 'NUL' THEN 1 ELSE 0 END AS "POINTS"
    FROM {{ ref('fct_matchs') }}
    UNION ALL
    SELECT 
        "SAISON_ID",
        "EQUIPE_EXTERIEUR_ID" AS "EQUIPE_ID",
        "BUTS_EXTERIEUR" AS "BUTS_POUR",
        "BUTS_DOMICILE" AS "BUTS_CONTRE",
        CASE WHEN "RESULTAT" = 'VICTOIRE_EXTERIEUR' THEN 3 WHEN "RESULTAT" = 'NUL' THEN 1 ELSE 0 END AS "POINTS"
    FROM {{ ref('fct_matchs') }}
)

SELECT 
    "SAISON_ID",
    "EQUIPE_ID",
    COUNT(*) AS "MATCHS_JOUES",
    SUM("POINTS") AS "TOTAL_POINTS",
    SUM("BUTS_POUR") AS "TOTAL_BUTS_POUR",
    SUM("BUTS_CONTRE") AS "TOTAL_BUTS_CONTRE",
    (SUM("BUTS_POUR") - SUM("BUTS_CONTRE")) AS "DIFFERENCE_BUTS"
FROM resultats_matchs
GROUP BY 1, 2
ORDER BY 1, 4 DESC, 7 DESC